# Generated by Django 5.0.6 on 2024-07-04 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('Job_position', models.CharField(max_length=200)),
                ('Job_type', models.CharField(max_length=200)),
                ('Job_duration', models.CharField(max_length=200)),
                ('Job_sector', models.CharField(max_length=200)),
                ('Job_description', models.CharField(max_length=500)),
                ('Job_location', models.CharField(max_length=200)),
                ('Company_description', models.CharField(max_length=1000)),
                ('Responsibilities', models.CharField(max_length=500)),
                ('Qualification', models.CharField(max_length=200)),
                ('Experience', models.CharField(max_length=200)),
                ('Skill', models.CharField(max_length=500)),
                ('Leewayzon_facility', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('Form_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=300)),
                ('Phone_number', models.CharField(max_length=200)),
                ('Experience_name', models.CharField(max_length=200)),
                ('Experience_company', models.CharField(max_length=200)),
                ('Experience_office_location', models.CharField(max_length=200)),
                ('Experience_description', models.CharField(max_length=500)),
                ('Experience_date_from', models.DateField(blank=True, null=True)),
                ('Experience_date_to', models.DateField(blank=True, null=True)),
                ('Education_institute', models.CharField(max_length=200)),
                ('Education_Major', models.CharField(max_length=200)),
                ('Education_Degree', models.CharField(max_length=200)),
                ('Education_school_location', models.CharField(max_length=200)),
                ('Education_description', models.CharField(max_length=500)),
                ('Education_date_from', models.DateField(blank=True, null=True)),
                ('Education_date_to', models.DateField(blank=True, null=True)),
                ('LinkedIn_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('Facebook_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('Twitter_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('Website_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('Resume', models.FileField(upload_to='resumes/')),
                ('Message', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
