# Generated by Django 5.0.6 on 2024-07-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_duration', models.CharField(max_length=200)),
                ('job_sector', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=200)),
                ('company_description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualification', models.TextField()),
                ('experience', models.CharField(max_length=200)),
                ('skill', models.TextField()),
                ('leewayzon_facility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_institute', models.CharField(max_length=200)),
                ('education_major', models.CharField(max_length=200)),
                ('education_degree', models.CharField(max_length=200)),
                ('education_school_location', models.CharField(max_length=200)),
                ('education_description', models.TextField()),
                ('education_date_from', models.DateField(blank=True, null=True)),
                ('education_date_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=200)),
                ('experience_company', models.CharField(max_length=200)),
                ('experience_office_location', models.CharField(max_length=200)),
                ('experience_description', models.TextField()),
                ('experience_date_from', models.DateField(blank=True, null=True)),
                ('experience_date_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=10)),
                ('linkedin_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('website_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth_job.job')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
