# Generated by Django 5.0.6 on 2024-07-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
