# Generated by Django 5.0.6 on 2024-07-08 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_job', '0002_application_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth_job.jobs'),
        ),
    ]
